apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "spring-label-dev" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: back-end-label # todo must match with deployment matchLabel
  ports:
    - port: 2255
      targetPort: 2255
---