spring.application.name=spring-food-app
server.port=2255

# todo Expose all management endpoints
management.endpoint.health.show-details=always
spring.main.allow-bean-definition-overriding=true

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=spring-food-app
management.tracing.sampling.probability=1.0



#APIKEY="4fae404d3ba2f8b487351adc51a3a429

management.metrics.export.datadog.enabled=true
management.metrics.export.datadog.api-key=YOUR_DATADOG_API_KEY
management.metrics.export.datadog.application-key=YOUR_DATADOG_APP_KEY
management.metrics.export.datadog.uri=https://api.datadoghq.com




api.v1.prefix=/api/v1
api.v2.prefix=/api/v2

#todo In application.properties or application.yml
#spring.profiles.active=prod,dev

#logging.file C:\Users\dnsri\Documents\elastic-stack.log

#TODO AWS properties
#amazon.dynamodb.endpoint = <YOUR_AWS_END_POINT>
#amazon.aws.accessKey = <YOUR_AWS_ACCESS_KEY>
#amazon.aws.secretKey = <YOUR_AWS_SECRET_KEY>
#amazon.aws.region =<YOUR_AWS_REGION>


#TODO: Google OAuth
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#spring.security.oauth2.client.registration.google.scope=profile,email


#TODO: Redis Cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

##todo to enable elastic search engine -> need to start proper Configuration
#logging.config=classpath:logback-spring.xml
#logging.file= C:\Users\dnsri\Documents\elastic-stack.log

#spring.datasource.url=jdbc:mysql://172.23.45.27:3306/spring
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#TODO : Mysql Database Configuration
#spring.datasource.url=jdbc:mysql://database-1.crgi8s6wwta0.ap-south-1.rds.amazonaws.com:3306/spring
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=admin
#spring.datasource.password=admin1234aA

# Hibernate Configuration
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
##spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate-ddl=true
#spring.jpa.properties.hibernate.show_sql=true

#todo PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#TODO : Database URL and credentials
#spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=your_password
#
## JDBC Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Hibernate settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## Show SQL queries in logs
#spring.jpa.show-sql=true

#TODO extra added
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.maximum-pool-size=1
#spring.datasource.hikari.minimum-idle=1
#spring.datasource.hikari.idle-timeout=60000
#spring.datasource.hikari.max-lifetime=1800000

#todo Apache Tomcat.
#server.tomcat.max-threads=200 # Maximum amount of worker threads.
#server.tomcat.min-spare-threads=10 # Minimum amount of worker threads.
#server.tomcat.accept-count=100 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
#server.tomcat.max-connections=10000 # Maximum number of connections that the server accepts and processes at any given time.


#TODO AWS RDS DATABASE CONNECTION
#spring.datasource.url=g.hibernate=DEBUG
#todo Oauth2Client
#spring.security.oauth2.client.registration.github.client-id=Ov23liASWYMZwakQpCvp
#spring.security.oauth2.client.registration.github.client-secret=ed66ed7878dac3515dac6c0b1f5a1ab3b1858b4f
#logging.level.org.springframework.security=TRACE
# Logging
#logging.level.org.springframework=ERROR
#logging.level.com.numericaideas=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#management.endpoints.web.exposure.include=*\
#management.endpoints.web.exposure.include= [ "prometheus" ]
#management.endpoint.health.show-details=always
#spring.main.allow-bean-definition-overriding=true
#TODO INSTALL AND DEPLOY IN DOCKER-> IMP
#1 docker pull MySQL:latest
#2 docker network create spring-network-mysql
#3 docker network ls
#4 docker run --name mysqldb --network spring-network-mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=foodapp -e MYSQL_USER=spring -e MYSQL_PASSWORD=root -d mysql:latest
#5 docker exec -it containerfastthreenumber bash
#6 mysql -uspring -proot
#7 spring.datasource.url=jdbc:mysqldb://localhost:3306/foodapp ->>change MySQL container name
#spring.datasource.username=spring
#spring.datasource.password=root
#8 clean mvn -> install Jarfile
#9 FROM openjdk:17
#EXPOSE 8080
#COPY target/docker-spring-image.jar .
#ENTRYPOINT ["java","-jar","/docker-spring-image.jar"]
#10 docker build -t docker-spring-image .
#11 docker run --network spring-network-MySQL --name springboot-container -p 8998:8998 -d repositeryname
#12 docker tag docker-spring-image:latest srinu641/kubernates ->optional
#docker push srinu641/kubernates:latest