apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argo-cd-k8s
  #  namespace: application
  labels:
    app: spring-mysql
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      #TODO: The default value is 25%.
      #TODO: maxUnavailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process.
      maxUnavailable: 20% # TODO: The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%).
      # TODO: maxSurge is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
      maxSurge: 20% # TODO: The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%).
  replicas: 3
  selector:
    matchLabels:
      app: spring-mysql
  template:
    metadata:
      labels:
        app: spring-mysql
    spec:
      containers:
        - name: spring-container-demo-app
          image: srinu641/spring-application-github:v1.01
          command: ["sh", "-c", "echo 'Initializing...'; sleep 5;"]
          #TODO: Always -> every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image digest.
          #TODO: Never-> the kubelet does not try fetching the image. If the image is somehow already present locally
          #TODO: IfNotPresent -> the image is pulled only if it is not already present locally.
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2255
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: POSTGRES_DB
#              value: spring
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
#              value: postgres
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
#              value: SRINU1234
              valueFrom:
                configMapKeyRef: #Todo secretKeyRef -> configMap not good to store DB passwords
                  name: postgres-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
  #  namespace: web-application
  labels:
    app: spring-app-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 2255
      targetPort: 2255
  selector:
    app: spring-mysql # TODO Should be match with deployment label name:
---


#1️⃣ Default Java application run
#command: ["java", "-jar", "/app/my-spring-boot-app.jar"]
#2️⃣ Run with a specific Spring profile
#command: ["java", "-jar", "/app/my-spring-boot-app.jar", "--spring.profiles.active=prod"]
#3️⃣ Run with JVM memory limits
#command: ["java", "-Xms256m", "-Xmx512m", "-jar", "/app/my-spring-boot-app.jar"]
#6️⃣ Run with logging config
#command: ["java", "-Dlogging.config=/app/logback.xml", "-jar", "/app/my-spring-boot-app.jar"]
#
#
#command: ["java"]
#args: ["-jar", "/app/my-spring-boot-app.jar"]
#
#command: ["java"]
#args: ["-jar", "/app/my-spring-boot-app.jar", "--spring.profiles.active=prod"]
#
#command: ["java"]
#args:
#  - "-Xms256m"
#  - "-Xmx512m"
#  - "-jar"
#  - "/app/my-spring-boot-app.jar"
#command: ["java"]
#args:
#  - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
#  - "-jar"
#  - "/app/my-spring-boot-app.jar"
#
