apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: database # todo get it from Helm values.yml
  labels:
    {{- include "spring-label-dev" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-end-label
  template:
    metadata:
      labels:
        {{- include "spring-label-dev" . | nindent 8 }}
    spec:
      containers:
        - name: spring-application-container
          image: {{ .Values.app.container.image }}
          resources:
            {{-}}
          ports:
            - containerPort: 2255
---
apiVersion: v1
kind: Service
metadata:
  name: ser-svc
  namespace: application-namespace
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: fargate-app
  ports:
    - port: 9988
      targetPort: 9988
---
