apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: spring
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: SRINU1234
---
#TODO Types of k8s Secrets:--> Opaque (default), [ TLS ],[ docker-registry ],[ basic-auth ],[ ssh-auth ]

#Todo  [ TLS ]
#  kubernetes.io/tls type Secret specifically used to store TLS certificates and private keys.
#  Commonly used for Ingress controllers or any service that requires SSL/TLS termination.

#TODO [ docker-registry ]
#  Stores Docker registry authentication information (username, password, email, and registry server).
#  Used to pull private images from container registries like Docker Hub, AWS ECR, GCR, etc.


apiVersion: v1
kind: Secret
metadata:
  name: postgres-passwd-secrets
type: Opaque
data:
  password: c3JpbnUxMjM0YUEK #srinu1234aA
---

